# Generated by Django 4.1.13 on 2024-04-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
