# Generated by Django 4.1.13 on 2024-04-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('category_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('des', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('mobile_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/mobiles/')),
                ('price', models.FloatField()),
                ('sale', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('des', models.TextField(null=True)),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mobile.brand')),
            ],
        ),
    ]
