# Generated by Django 4.1.13 on 2024-04-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.ImageField(null=True, upload_to='image/mobiles/'),
        ),
    ]
