# Generated by Django 4.1.13 on 2024-04-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_mobile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='brand',
            new_name='brand_id',
        ),
    ]
