# Generated by Django 4.1.13 on 2024-04-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_rename_brand_mobile_brand_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='category_id',
            new_name='brand_id',
        ),
    ]
