# Generated by Django 4.1.13 on 2024-04-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='description',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='description',
            new_name='des',
        ),
    ]
