# Generated by Django 4.1.13 on 2024-04-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='author_id',
            field=models.ManyToManyField(to='book.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.ManyToManyField(to='book.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_id',
            field=models.ManyToManyField(to='book.publisher'),
        ),
    ]
